// WHAT IS A BINARY HEAP?
    // A TREE STRUCTURE BUT HAS DIFFERENT RULES
    // IN A MAXBINARYHEAP, PARENT NODES ARE ALWAYS LARGER THAN CHILD NODES
        // EACH PARENT HAS AT MOST TWO CHILD NODES
        // PARENTS VAL IS GREATER THAN CHILDREN BUT NO GUARANTEES BETWEEN SIBLING NODES
        // A BINARY HEAP IS AS COMPACT AS POSSIBLE. 
        // ALL CHILDREN OF EACH NODE ARE AS FULL AS THEY CAN BE AND LEFT CHILDREN ARE FILL OUT FIRST
    
    
        // IN A MINBINARYHEAP, PARENT NODES ARE AWAYS SMALLER THAN CHILD NODES
