// WHAT IS A HASH TABLE(HASH MAP): USED TO STORE KEY-VALUE PAIRS; ARE LIKE ARRAYS BUT KEYS ARE NOT ORDERED
    // UNLIKE ARRAYS, HASHTABLES ARE FAST FOR ALL OF THE FOLLOWING OPERATIONS, FINDING VALUES, ADDING NEW VALUES, AND REMOVING VALUES

// PYTHON HAS DICTIONARIES
// JAVASCRIPT HAS OBJECTS AND MAPS
// JAVA, GO, & SCALA HAVE MAPS
// RUBY HAS HASHES